### ISSUE TITLE
Face for placeholders?

### ISSUE THREAD

**Issue by protesilaos** [oantolin/placeholder#1]
If you need some ideas for a face that is applied to the inserted string, this could be a start:

```elisp
(defface placeholder
  '((((class color) (min-colors 88) (background dark)) :foreground "#60cfa2")
    (((class color) (min-colors 88) (background light)) :foreground "#005040")
    (t :foreground "green"))
  "Face for `placeholder-insert' strings.")
```

The intention is to keep it fairly unobtrusive.  Otherwise there could also be a bold weight or a subtle background.

Demo:

![Screenshot at 2020-04-17 22-07-16](https://user-images.githubusercontent.com/12828033/79605152-14f3fb00-80f8-11ea-9006-6bb693569fe9.png)

![Screenshot at 2020-04-17 22-07-25](https://user-images.githubusercontent.com/12828033/79605164-18878200-80f8-11ea-98f6-0657c403f283.png)

**Comment by oantolin** [comment]
I like the idea and the subtle colors, thanks!

**Comment by protesilaos** [comment]
You are welcome!
